[package]
name = "xstore"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-utils = "0.8.8"
cid = "0.8.0"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "xstore"
harness = false
